-- INSERT INTO account (name, amount) VALUES ('Helen Down', 1000);
-- INSERT INTO account (name, amount) VALUES ('Peter Read', 1000);
-- INSERT INTO account (id, name, amount) VALUES (1, 'Helen Down', 1000);
-- INSERT INTO account (id, name, amount) VALUES (2, 'Peter Read', 1000);